### ISSUE TITLE
puppeteer-chrome invalid handle

### ISSUE THREAD

**Issue by zifnub** [drizzle-mizzle/Character-Engine-Discord#15]
Config is correct & the bot is added with the required auth.

Downloading browser...
Path: E:\Character-Engine-Discord\puppeteer-chrome
Unhandled exception. System.IO.IOException: The handle is invalid.
   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.ConsolePal.get_WindowWidth()
   at CharacterEngineDiscord.Services.CommonService.LogException(Object[] text) in E:\Character-Engine-Discord\Services\CommonService\CommonLogsService.cs:line 36
   at CharacterEngineDiscord.Services.DiscordService.SetupIntegrationAsync() in E:\Character-Engine-Discord\Services\DiscordService.cs:line 246
   at CharacterEngineDiscord.Services.DiscordService.SetupDiscordClient() in E:\Character-Engine-Discord\Services\DiscordService.cs:line 39
   at CharacterEngineDiscord.Program.MainAsync() in E:\Character-Engine-Discord\Program.cs:line 31
   at CharacterEngineDiscord.Program.Main() in E:\Character-Engine-Discord\Program.cs:line 10

**Comment by drizzle-mizzle** [comment]
fixed

**Comment by zifnub** [comment]
Thanks!
