### ISSUE TITLE
System.AggregateException

### ISSUE THREAD

**Issue by zifnub** [drizzle-mizzle/Character-Engine-Discord#17]
After the last fix I can connect fine but its still throwing this:

Path: E:\LLM\Character-Engine-Discord\puppeteer-chrome
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
System.AggregateException: One or more errors occurred. (One or more errors occurred. (The handle is invalid.))
 ---> System.AggregateException: One or more errors occurred. (The handle is invalid.)
 ---> System.IO.IOException: The handle is invalid.
   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.ConsolePal.GetCursorPosition()
   at PuppeteerLib.PuppeteerLib.TryToDownloadBrowserAsync(String path)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at CharacterAI.Client.CharacterAiClient..ctor(String customBrowserDirectory, String customBrowserExecutablePath)
   at CharacterEngineDiscord.Services.IntegrationsService.LaunchCaiAsync() in E:\LLM\Character-Engine-Discord\Services\IntegrationsService.cs:line 85
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at CharacterEngineDiscord.Services.IntegrationsService.Initialize() in E:\LLM\Character-Engine-Discord\Services\IntegrationsService.cs:line 74
   at CharacterEngineDiscord.Services.DiscordService.SetupIntegrationAsync() in E:\LLM\Character-Engine-Discord\Services\DiscordService.cs:line 280

**Comment by drizzle-mizzle** [comment]
What terminal do you use?

**Comment by zifnub** [comment]
MobaXterm

**Comment by drizzle-mizzle** [comment]
Try simple bash/zsh. 
C# IO doesn't pal with exotic consoles for some reason. I'll make it safe from errors like this a bit later

**Comment by zifnub** [comment]
Thanks, not having any issues when retrying in cmd.
